apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec: 
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: 1st
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html

